// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whcxxbojlgdfcqblilmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoY3h4Ym9qbGdkZmNxYmxpbG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTg2NTEsImV4cCI6MjA3MjczNDY1MX0.3SWf9bKCvNdiN0LzJGRmO7oFokBXYKd-XUbvCo131nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});